# Generated by Django 2.1 on 2019-02-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='displayed_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
